export const odriSeatsMam = [
  {
    seats: [
      [
        {
          id: '19149',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19150',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19151',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19152',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19153',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
      ],
      [
        {
          id: '19154',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19155',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19156',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19157',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19158',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
      ],
      [
        {
          id: '19159',
          type: 'SEAT',
          number: '76',
          coords: '3:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19160',
          type: 'SEAT',
          number: '77',
          coords: '3:2',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19161',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19162',
          type: 'SEAT',
          number: '78',
          coords: '3:4',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19163',
          type: 'SEAT',
          number: '79',
          coords: '3:5',
          status: 'BUSY',
          isSelected: false,
        },
      ],
      [
        {
          id: '19164',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19165',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19166',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19167',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19168',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
      ],
      [
        {
          id: '19169',
          type: 'SEAT',
          number: '60',
          coords: '5:1',
          status: 'FREE',
          isSelected: false,
        },
        {
          id: '19170',
          type: 'SEAT',
          number: '61',
          coords: '5:2',
          status: 'FREE',
          isSelected: false,
        },
        {
          id: '19171',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19172',
          type: 'SEAT',
          number: '62',
          coords: '5:4',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19173',
          type: 'SEAT',
          number: '63',
          coords: '5:5',
          status: 'BUSY',
          isSelected: false,
        },
      ],
      [
        {
          id: '19174',
          type: 'SEAT',
          number: '64',
          coords: '6:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19175',
          type: 'SEAT',
          number: '65',
          coords: '6:2',
          status: 'FREE',
          isSelected: false,
        },
        {
          id: '19176',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19177',
          type: 'SEAT',
          number: '66',
          coords: '6:4',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19178',
          type: 'SEAT',
          number: '67',
          coords: '6:5',
          status: 'BUSY',
          isSelected: false,
        },
      ],
      [
        {
          id: '19179',
          type: 'SEAT',
          number: '68',
          coords: '7:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19180',
          type: 'SEAT',
          number: '69',
          coords: '7:2',
          status: 'FREE',
          isSelected: false,
        },
        {
          id: '19181',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19182',
          type: 'SEAT',
          number: '70',
          coords: '7:4',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19183',
          type: 'SEAT',
          number: '71',
          coords: '7:5',
          status: 'BUSY',
          isSelected: false,
        },
      ],
      [
        {
          id: '19184',
          type: 'SEAT',
          number: '72',
          coords: '8:1',
          status: 'FREE',
          isSelected: false,
        },
        {
          id: '19185',
          type: 'SEAT',
          number: '73',
          coords: '8:2',
          status: 'FREE',
          isSelected: false,
        },
        {
          id: '19186',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19187',
          type: 'SEAT',
          number: '74',
          coords: '8:4',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19188',
          type: 'SEAT',
          number: '75',
          coords: '8:5',
          status: 'BUSY',
          isSelected: false,
        },
      ],
      [
        {
          id: '19189',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19190',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19191',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19192',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19193',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
      ],
      [
        {
          id: '19194',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19195',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19196',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19197',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19198',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
      ],
    ],
  },
  {
    seats: [
      [
        {
          id: '19249',
          type: 'SEAT',
          number: '1',
          coords: '1:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19250',
          type: 'SEAT',
          number: '2',
          coords: '1:2',
          status: 'FREE',
          isSelected: false,
        },
        {
          id: '19251',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19252',
          type: 'SEAT',
          number: '3',
          coords: '1:4',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19253',
          type: 'SEAT',
          number: '4',
          coords: '1:5',
          status: 'BUSY',
          isSelected: false,
        },
      ],
      [
        {
          id: '19254',
          type: 'SEAT',
          number: '5',
          coords: '2:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19255',
          type: 'SEAT',
          number: '6',
          coords: '2:2',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19256',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19257',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19258',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
      ],
      [
        {
          id: '19259',
          type: 'SEAT',
          number: '9',
          coords: '3:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19260',
          type: 'SEAT',
          number: '10',
          coords: '3:2',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19261',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19262',
          type: 'SEAT',
          number: '7',
          coords: '3:4',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19263',
          type: 'SEAT',
          number: '8',
          coords: '3:5',
          status: 'BUSY',
          isSelected: false,
        },
      ],
      [
        {
          id: '19264',
          type: 'SEAT',
          number: '13',
          coords: '4:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19265',
          type: 'SEAT',
          number: '14',
          coords: '4:2',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19266',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19267',
          type: 'SEAT',
          number: '11',
          coords: '4:4',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19268',
          type: 'SEAT',
          number: '12',
          coords: '4:5',
          status: 'BUSY',
          isSelected: false,
        },
      ],
      [
        {
          id: '19269',
          type: 'SEAT',
          number: '17',
          coords: '5:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19270',
          type: 'SEAT',
          number: '18',
          coords: '5:2',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19271',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19272',
          type: 'SEAT',
          number: '15',
          coords: '5:4',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19273',
          type: 'SEAT',
          number: '16',
          coords: '5:5',
          status: 'BUSY',
          isSelected: false,
        },
      ],
      [
        {
          id: '19274',
          type: 'SEAT',
          number: '21',
          coords: '6:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19275',
          type: 'SEAT',
          number: '22',
          coords: '6:2',
          status: 'FREE',
          isSelected: false,
        },
        {
          id: '19276',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19277',
          type: 'SEAT',
          number: '19',
          coords: '6:4',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19278',
          type: 'SEAT',
          number: '20',
          coords: '6:5',
          status: 'BUSY',
          isSelected: false,
        },
      ],
      [
        {
          id: '19279',
          type: 'SEAT',
          number: '25',
          coords: '7:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19280',
          type: 'SEAT',
          number: '26',
          coords: '7:2',
          status: 'FREE',
          isSelected: false,
        },
        {
          id: '19281',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19282',
          type: 'SEAT',
          number: '23',
          coords: '7:4',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19283',
          type: 'SEAT',
          number: '24',
          coords: '7:5',
          status: 'BUSY',
          isSelected: false,
        },
      ],
      [
        {
          id: '19284',
          type: 'SEAT',
          number: '29',
          coords: '8:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19285',
          type: 'SEAT',
          number: '30',
          coords: '8:2',
          status: 'FREE',
          isSelected: false,
        },
        {
          id: '19286',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19287',
          type: 'SEAT',
          number: '27',
          coords: '8:4',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19288',
          type: 'SEAT',
          number: '28',
          coords: '8:5',
          status: 'BUSY',
          isSelected: false,
        },
      ],
      [
        {
          id: '19289',
          type: 'SEAT',
          number: '31',
          coords: '9:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19290',
          type: 'SEAT',
          number: '32',
          coords: '9:2',
          status: 'FREE',
          isSelected: false,
        },
        {
          id: '19291',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19292',
          type: 'SEAT',
          number: '35',
          coords: '9:4',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19293',
          type: 'SEAT',
          number: '36',
          coords: '9:5',
          status: 'BUSY',
          isSelected: false,
        },
      ],
      [
        {
          id: '19294',
          type: 'SEAT',
          number: '33',
          coords: '10:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19295',
          type: 'SEAT',
          number: '34',
          coords: '10:2',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19296',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19297',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19298',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
      ],
      [
        {
          id: '19299',
          type: 'SEAT',
          number: '37',
          coords: '11:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19300',
          type: 'SEAT',
          number: '38',
          coords: '11:2',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19301',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19302',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19303',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
      ],
      [
        {
          id: '19304',
          type: 'SEAT',
          number: '41',
          coords: '12:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19305',
          type: 'SEAT',
          number: '42',
          coords: '12:2',
          status: 'FREE',
          isSelected: false,
        },
        {
          id: '19306',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19307',
          type: 'SEAT',
          number: '39',
          coords: '12:4',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19308',
          type: 'SEAT',
          number: '40',
          coords: '12:5',
          status: 'BUSY',
          isSelected: false,
        },
      ],
      [
        {
          id: '19309',
          type: 'SEAT',
          number: '45',
          coords: '13:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19310',
          type: 'SEAT',
          number: '46',
          coords: '13:2',
          status: 'FREE',
          isSelected: false,
        },
        {
          id: '19311',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19312',
          type: 'SEAT',
          number: '43',
          coords: '13:4',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19313',
          type: 'SEAT',
          number: '44',
          coords: '13:5',
          status: 'BUSY',
          isSelected: false,
        },
      ],
      [
        {
          id: '19314',
          type: 'SEAT',
          number: '51',
          coords: '14:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19315',
          type: 'SEAT',
          number: '52',
          coords: '14:2',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19316',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19317',
          type: 'SEAT',
          number: '47',
          coords: '14:4',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19318',
          type: 'SEAT',
          number: '48',
          coords: '14:5',
          status: 'BUSY',
          isSelected: false,
        },
      ],
      [
        {
          id: '19319',
          type: 'SEAT',
          number: '53',
          coords: '15:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19320',
          type: 'SEAT',
          number: '54',
          coords: '15:2',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19321',
          type: null,
          number: null,
          coords: null,
          status: null,
          isSelected: null,
        },
        {
          id: '19322',
          type: 'SEAT',
          number: '49',
          coords: '15:4',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19323',
          type: 'SEAT',
          number: '50',
          coords: '15:5',
          status: 'BUSY',
          isSelected: false,
        },
      ],
      [
        {
          id: '19324',
          type: 'SEAT',
          number: '55',
          coords: '16:1',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19325',
          type: 'SEAT',
          number: '56',
          coords: '16:2',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19326',
          type: 'SEAT',
          number: '57',
          coords: '16:3',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19327',
          type: 'SEAT',
          number: '58',
          coords: '16:4',
          status: 'BUSY',
          isSelected: false,
        },
        {
          id: '19328',
          type: 'SEAT',
          number: '59',
          coords: '16:5',
          status: 'BUSY',
          isSelected: false,
        },
      ],
    ],
  },
];
