export const faqConstans = {
  '/faq/bronjuvannja-mists': {
    id: 1,
    title: 'booking_seats',
    questions: [
      {
        id: 1,
        title: 'concession_tickets',
        slug: 'discount-tickets',
        text: ['text_1'],
      },
      {
        id: 2,
        title: 'border_crossing',
        slug: 'border-crossing',
        text: ['text_1', 'text_2'],
      },
      {
        id: 3,
        title: 'can_send_parcel',
        slug: 'can-you-send-a-package',
        text: ['text_1'],
      },
      {
        id: 4,
        title: 'can_skip_printing',
        slug: 'can-you-not-print-the-ticket',
        text: ['text_1', 'text_2'],
      },
      {
        id: 5,
        title: 'how_to_book',
        slug: 'how-to-book-a-ticket',
        text: ['text_1', 'text_2'],
      },
      {
        id: 6,
        title: 'free_seating_how_to_choose',
        slug: 'free-seating-how-to-choose-a-seat',
        text: ['text_1', 'text_2'],
      },
      {
        id: 7,
        title: 'international_flights',
        slug: 'international-flights',
        text: ['text_1', 'text_2'],
      },
      {
        id: 8,
        title: 'payment_and_receiving',
        slug: 'how-to-pay-and-receive-tickets',
        text: ['text_1', 'text_2'],
      },
      {
        id: 9,
        title: 'available_discounts',
        slug: 'discounts-promotions-and-promo-codes',
        text: ['text_1'],
      },
      {
        id: 10,
        title: 'how_to_leave_review',
        slug: 'how-to-leave-feedback-about-trip-and-carrier',
        text: ['text_1', 'text_2'],
      },
    ],
  },
  '/faq/routes-and-buses': {
    id: 1,
    title: 'flights_and_buses',
    questions: [
      {
        id: 1,
        title: 'available_flights_schedule',
        slug: 'available-flights-schedules',
        text: ['text_1', 'text_2'],
      },
      {
        id: 2,
        title: 'flight_confirmation',
        slug: 'is-the-flight-confirmed',
        text: ['text_1', 'text_2', 'text_3'],
      },
      {
        id: 3,
        title: 'ticket_purchase_advance',
        slug: 'how-far-in-advance-to-buy-ticket',
        text: ['text_1'],
      },
      {
        id: 4,
        title: 'calculate_travel_time',
        slug: 'how-to-calculate-travel-time-and-arrival-time',
        text: ['text_1', 'text_2'],
      },
      {
        id: 5,
        title: 'bus_type',
        slug: 'what-type-of-bus-will-it-be',
        text: ['text_1', 'text_2'],
      },
      {
        id: 6,
        title: 'travel_with_pets',
        slug: 'travel-with-pets',
        text: ['text_1', 'text_2'],
      },
      {
        id: 7,
        title: 'luggage_transportation',
        slug: 'luggage-transportation',
        text: ['text_1', 'text_2'],
      },
      {
        id: 8,
        title: 'route_and_stops',
        slug: 'route-and-stops',
        text: ['text_1'],
      },
      {
        id: 9,
        title: 'if_no_route_found',
        slug: 'if-you-cant-find-the-flight-you-need',
        text: ['text_1'],
      },
      {
        id: 10,
        title: 'what_you_need_for_boarding',
        slug: 'what-you-need-for-boarding',
        text: ['text_1', 'text_2'],
      },
      {
        id: 12,
        title: 'how_early_to_arrive_before_flight',
        slug: 'how-early-to-arrive-before-flight',
        text: ['text_1', 'text_2'],
      },
      {
        id: 13,
        title: 'exact_departure_address_how_to_find_the_bus',
        slug: 'exact-departure-address-how-to-find-the-bus',
        text: ['text_1', 'text_2'],
      },
      {
        id: 14,
        title: 'departure_and_arrival_time',
        slug: 'departure-and-arrival-time',
        text: ['text_1', 'text_2'],
      },
    ],
  },
  '/faq/ticket-refund': {
    id: 1,
    title: 'ticket_refund',
    questions: [
      {
        id: 1,
        title: 'what_to_do_if_passenger_details_are_incorrect_in_ticket',
        slug: 'what-to-do-if-passenger-details-are-incorrect-in-ticket',
        text: ['text_1', 'text_2', 'text_3'],
      },
      {
        id: 2,
        title: 'how_to_process_refund',
        slug: 'how-to-process-refund',
        text: ['text_1', 'text_2', 'text_3'],
      },
      {
        id: 3,
        title: 'how_to_know_return_terms_and_conditions',
        slug: 'how-to-know-return-terms-and-conditions',
        text: ['text_1', 'text_2', 'text_3'],
      },
      {
        id: 4,
        title: 'can_i_change_flight_date_or_time',
        slug: 'can-i-change-flight-date-or-time',
        text: ['text_1', 'text_2', 'text_3'],
      },
      {
        id: 5,
        title: 'what_to_do_if_you_missed_the_flight',
        slug: 'what-to-do-if-you-missed-the-flight',
        text: ['text_1', 'text_2', 'text_3'],
      },
      {
        id: 6,
        title: 'what_to_do_if_my_flight_is_cancelled_or_bus_did_not_arrive',
        slug: 'what-to-do-if-my-flight-is-cancelled-or-bus-did-not-arrive',
        text: ['text_1', 'text_2', 'text_3', 'text_4'],
      },
      {
        id: 7,
        title: 'what_to_do_if_i_have_problems_during_trip',
        slug: 'what-to-do-if-i-have-problems-during-trip',
        text: ['text_1', 'text_2'],
      },
    ],
  },
};
