export const OCTOBUS_DOC_TYPES = ['PASSPORT', 'TRAVEL_PASSPORT', 'BIRTH_CERTIFICATE'];
export const INFOBUS_DOC_TYPES = ['ID_CARD', 'FOREIGN_PASSPORT'];
export const INFOBUS_GENDER = ['MALE', 'FEMALE'];
