import { Params } from "@/types/common.types";

export const generateMetadata = async ({ params }: { params: Params }) => {
  const { lng } = await params;
  return {
    title: `NextJS i18n Template - ${lng.toUpperCase()}`,
    description: "Generated by Create Next App and i18next",
  };
};

export default async function MainLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Params;
}>) {
  const { lng } = await params;
  return (
    <div>
      <div>{lng}</div>
      {children}
    </div>
  );
}
